name: Check And Build Pages

on:
  workflow_dispatch:
  pull_request:

jobs:
  check-html:
    name: Check And Build Pages
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: noetic
    - uses: actions/setup-python@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '2.7'
    - name: Run htmlproofer.sh
      run: ./htmlproofer.sh
